import type { GameEvent } from "../schema/event.js";
import type { GameState } from "../schema/state.js";
import { reduceAll } from "./reduce.js";

/**
 * Rewind.
 *
 * This is essentially free, and it is worth understanding why: the journal is append-only
 * and the reducer is pure and deterministic, so "the world at turn N" is just the fold of
 * the first N root events over the authored starting state. There is nothing to undo,
 * because nothing was ever destroyed — we simply stop replaying earlier.
 *
 * Consequences worth knowing:
 *   · There is no depth limit. Rewinding to turn 3 from turn 400 is as exact as rewinding
 *     one turn, because both are the same operation.
 *   · Rewinding cannot corrupt anything. The events it drops are archived to a branch file
 *     rather than deleted, so a rewind is itself reversible.
 *   · Cost is O(turns replayed), which at a few hundred turns is milliseconds. If a save
 *     ever grows enough to matter, `snapshotEvery` below is the fix, not a redesign.
 */

export interface RewindResult {
  state: GameState;
  /** Events removed from the timeline, in order. Archive these, never drop them. */
  removed: GameEvent[];
  /** Events that remain the canonical timeline. */
  kept: GameEvent[];
  toTurn: number;
  truncated: boolean;
}

export function rewind(
  initial: GameState,
  journal: readonly GameEvent[],
  toTurn: number,
): RewindResult {
  if (toTurn < 0) throw new RangeError(`Cannot rewind to turn ${toTurn}`);

  // Cascades are regenerated by replay, so the timeline is defined by root events alone.
  const roots = journal.filter((e) => e.derived_from === null);
  const kept = roots.filter((e) => e.turn <= toTurn);
  const removed = roots.filter((e) => e.turn > toTurn);

  const replayed = reduceAll(initial, kept);

  return { state: replayed.state, removed, kept, toTurn, truncated: replayed.truncated };
}

/** Rewind by a number of turns rather than to an absolute one. */
export function rewindBy(
  initial: GameState,
  journal: readonly GameEvent[],
  turns: number,
): RewindResult {
  const current = highestTurn(journal);
  return rewind(initial, journal, Math.max(0, current - turns));
}

export function highestTurn(journal: readonly GameEvent[]): number {
  return journal.reduce((n, e) => Math.max(n, e.turn), 0);
}

/**
 * A readable timeline for a "pick a point to return to" UI. One row per turn, with what
 * the player did and what it set off.
 */
export interface TimelineRow {
  turn: number;
  type: string;
  summary: string;
  cascades: number;
  world_minute: number;
}

/**
 * The log, one row per turn.
 *
 * `names` resolves an id to what a person would call it. Optional because the engine has
 * callers with no world in hand, but every player-facing one should pass it: "spoke with
 * npc_cotter about loc_moot_hall" is not a log, it is a stack trace — and it is also
 * unmatchable when somebody later asks to be taken back to before they talked to Cotter.
 */
export function timeline(journal: readonly GameEvent[], names?: (id: string) => string): TimelineRow[] {
  const roots = journal.filter((e) => e.derived_from === null);
  return roots.map((e) => {
    const cascades = journal.filter((c) => c.derived_from === e.id).length;
    return {
      turn: e.turn,
      type: e.type,
      summary: summarize(e, names ?? ((id) => id)),
      cascades,
      world_minute: e.world_minute,
    };
  });
}

function summarize(e: GameEvent, names: (id: string) => string): string {
  const p = e.payload as Record<string, unknown>;
  const who = e.target_ids.map(names).join(", ");
  switch (e.type) {
    case "move": {
      // A zone move inside a fight carries no destination location, only a zone.
      const to = String(p["to"] ?? "");
      const zone = String(p["zone"] ?? "");
      if (to) return `went to ${names(to)}`;
      return zone ? `crossed to ${zone.replace(/^z_/, "").replace(/_/g, " ")}` : "moved";
    }
    case "attack": return `attacked ${who}${p["hit"] ? ` (hit for ${String(p["damage"])})` : " (missed)"}`;
    case "skill_check": {
      const kind = String(p["kind"] ?? "");
      if (kind) return `spent hours ${kind.replace(/_/g, " ")}${p["topic"] ? ` about ${String(p["topic"])}` : ""}`;
      return `${String(p["skill"] ?? "check")} vs DC ${String(p["dc"] ?? "?")} — ${String(p["outcome"] ?? "")}`;
    }
    case "dialogue": return `spoke with ${who}${p["topic"] ? ` about ${String(p["topic"])}` : ""}`;
    case "item_transfer": return `took ${String(p["def_id"] ?? "something")}`;
    case "rest": return `${String(p["kind"] ?? "short")} rest`;
    case "time_pass": return `waited ${String(p["minutes"] ?? "")} minutes`;
    case "observe": return "looked around";
    default: return e.type;
  }
}

/**
 * Which turns to keep full snapshots at, if replay cost ever becomes noticeable.
 * Unused today — present so the answer to "what if a campaign runs to turn 5000" is a
 * three-line change rather than an architecture conversation.
 */
export function snapshotEvery(turn: number, interval = 50): boolean {
  return turn > 0 && turn % interval === 0;
}
