import { describe, expect, it } from "vitest";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { loadCampaign } from "../../src/content/loadCampaign.js";
import { DEMO_SCRIPT } from "../../src/content/demoScript.js";
import { runScript } from "../../src/engine/session.js";
import { reduceAll } from "../../src/engine/reduce.js";
import { stable } from "../../src/state/jsonFileStore.js";

const CAMPAIGN = path.join(
  path.dirname(fileURLToPath(import.meta.url)),
  "../../content/campaign/drowned_bell",
);

/**
 * These suites test that the ENGINE is deterministic — replay, rewind, cascades. They pin
 * `committed` dice so a re-run of the same script is comparable. Dice *feel* is tested in
 * tests/rules/.
 */
async function loadCommitted() {
  const s = structuredClone(await loadCampaign(CAMPAIGN));
  s.meta.session_zero.dice = "committed";
  return s;
}

/**
 * THE PHASE 0 GATE.
 *
 * A scripted thirty-action sequence runs, and replaying the journal reproduces the exact
 * final state, byte for byte. If this passes, the journal is genuinely the source of
 * truth and every other save file is a cache — which is what buys undo, save-scumming,
 * and the confidence to let an LLM anywhere near this thing in phase 1.
 */
describe("golden: journal replay reproduces state exactly", () => {
  it("runs 30 actions and replays to a byte-identical world", async () => {
    const initial = await loadCommitted();

    const live = runScript(initial, DEMO_SCRIPT);
    expect(DEMO_SCRIPT.length).toBeGreaterThanOrEqual(30);

    // Replay consumes only root events. Cascades are regenerated by the reducer, which is
    // the stronger claim: the trigger graph is deterministic, not just recorded.
    const roots = live.journal.filter((e) => e.derived_from === null);
    expect(roots.length).toBeGreaterThan(0);

    const replayed = reduceAll(initial, roots);

    expect(stable(replayed.state)).toBe(stable(live.state));
  });

  it("replays identically a second time, from the same journal", async () => {
    const initial = await loadCommitted();
    const live = runScript(initial, DEMO_SCRIPT);
    const roots = live.journal.filter((e) => e.derived_from === null);

    const a = reduceAll(initial, roots);
    const b = reduceAll(initial, roots);

    expect(stable(a.state)).toBe(stable(b.state));
  });

  it("produces the same world when the whole script is run twice", async () => {
    const initial = await loadCommitted();
    const a = runScript(initial, DEMO_SCRIPT);
    const b = runScript(initial, DEMO_SCRIPT);

    expect(stable(a.state)).toBe(stable(b.state));
    expect(a.journal.map((e) => e.id)).toEqual(b.journal.map((e) => e.id));
  });

  it("never leaves the cascade depth limit tripped", async () => {
    const initial = await loadCommitted();
    const live = runScript(initial, DEMO_SCRIPT);
    const roots = live.journal.filter((e) => e.derived_from === null);
    expect(reduceAll(initial, roots).truncated).toBe(false);
  });

  it("advances the world clock and the turn counter", async () => {
    const initial = await loadCommitted();
    const live = runScript(initial, DEMO_SCRIPT);

    // Every root event is a turn — including the CPU's combat turns.
    expect(live.state.meta.turn).toBe(live.journal.filter((e) => e.derived_from === null).length);
    expect(live.state.world.world_minute).toBeGreaterThan(initial.world.world_minute);
  });
});
